sonar.projectKey=wilsonify_pyknit
sonar.organization=wilsonify

sonar.sources=pyknit/
sonar.tests=test/
sonar.python.version=3.9,3.10,3.11,3.12,3.13,3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8
